resources:
  - name: propertyCanvas
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: buildInfoTrigger
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
  - name: gitResCanvas
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
pipelines:
  - name: trigger_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2: 2
          priority: 0
          inputResources:
            - name: propertyCanvas
            - name: buildInfoTrigger
            - name: gitResCanvas
        execution:
          onExecute:
            - printenv
            - echo "done"
#       - name: jenkins
#         type: Jenkins
#         configuration:
#           jenkinsJobName: somename
#           integrations:
#             - name: jenkins
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: g1
          environmentVariables:
            step2env1: 1
            step2env2: 2
          inputSteps:
            - name: trigger_1
#             - name: jenkins
          inputResources:
            - name: propertyCanvas
            - name: buildInfoTrigger
            - name: gitResCanvas
        execution:
          onExecute:
            - printenv
            - echo "done"
      - name: postTrigger
        type: PostMatrix
        configuration:
          environmentVariables:
            postenv1: 1
            postenv2: 2
          inputSteps:
            - name: trigger_1
#             - name: jenkins
          inputResources:
            - name: propertyCanvas
            - name: buildInfoTrigger
            - name: gitResCanvas
        execution:
          onExecute:
            - echo "done"
#       - name: trigger_3
#         type: Bash
#         configuration:
#           affinityGroup: g2
#           inputSteps:
#             - name: trigger_2
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_4
#         type: Bash
#         configuration:
#           affinityGroup: g2
#           inputSteps:
#             - name: trigger_3
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_5
#         type: Bash
#         configuration:
#           affinityGroup: g1
#           inputSteps:
#             - name: trigger_1
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_6
#         type: Bash
#         configuration:
#           affinityGroup: g2
#           inputSteps:
#             - name: trigger_4
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_7
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: trigger_5
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_8
#         type: Bash
#         configuration:
#           inputResources:
#             - name: buildInfoTrigger
#           inputSteps:
#             - name: trigger_1
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_9
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: trigger_1
#           outputResources:
#             - name: propertyCanvas
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_10
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: trigger_1
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_11
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: trigger_7
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_12
#         type: Bash
#         configuration:
#           inputResources:
#             - name: propertyCanvas
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"
#       - name: trigger_13
#         type: Bash
#         configuration:
#           affinityGroup: g2
#           inputSteps:
#             - name: trigger_4
#           inputResources:
#             - name: gitResCanvas
#         execution:
#           onExecute:
#             - sleep 60
#             - echo "done"

